### PR TITLE
RFC for wysiwym plugins.

### PR DESCRIPTION
**Pull request by jpuri**
Make tina prosemirror based Wysiwym extensible by using plugins.

[Rendered text](https://github.com/tinacms/rfcs/blob/84e89865adec2fad3595708b3afe80b40806b30d/0007-tinacms-wysiwym-plugins.md)

### CODE REVIEW

**Comment by ncphillips** [comment]
This is awesome 👍 

Could we add some simple examples of these? They don't need to be robust examples, basically pseudocode is fine. Just enough to get a sense of what they will be used for and why. 

Maybe add the rough TS interface. From what you wrote I think it's:

```ts
import { FC } from "react"
import { Plugin as ProsemirroPlugin } from "prosemirror-state"
import { EditorView } from "prosemirror-view"
import { NodeSpec, MarkSpec } from "prosemirror-model"

interface WysiwygPlugin {

  plugin: ProsemirrorPlugin 

  Menu: FC<WidgetProps>

  Popup: FC<WidgetProps>

  schema: {
    nodes: {
      [key: string]: NodeSpec
    }
    marks: {
      [key: string]: MarkSpec
    }

  markdownTranslator(...): ...
}

interface WidgeProps {
  view: EditorView
}
```

It's not really clear to me what it would be for `markdownTranslator` though. That's the one I'm particularly interested in seeing an example for.

**Comment by jpuri** [comment]
Hey @ncphillips : sounds good, I will add an example to this.

Actually, I also need to work on exact details for translator. Some changes will be required in current translator code also to make it extensible.

**Comment by ncphillips** [comment]
Okay 👌

One approach could be to leave the translator/schema parts out of this particular RFC. The first pass could just introduce the basic plugin API and only accept Prosemirror plugins and the menu/popup components. Once that fundamental structure is in place the the translator/schema changes could be explored with greater focus.

**Comment by jpuri** [comment]
Hey @ncphillips : I added an example of `embed` plugin [here](https://github.com/tinacms/rfcs/blob/84e89865adec2fad3595708b3afe80b40806b30d/0007-tinacms-wysiwym-plugins.md).

**Comment by DirtyF** [comment]
Curious to hear if @BPScott has some feedback about this RFC 😊

**Comment by BPScott** [comment]
> Curious to hear if @BPScott or @kaelig have some feedback about this RFC 

👋 I've not had the time do anything more than faintly scratch the surface of wysiwym stuff, so I've got no opinions on how to structure this going forward and haven't got any particular use-cases in mind currently. Thanks for thinking of us but I've got nothing to contribute other than saying I trust y'all :)

**Pull request merged**
